version: '3'

services:
  app:
    container_name: app
    tty: true
    build:
      context: node
    volumes:
      - ./node:/usr/src/app
    networks:
      - node-network
    ports:
      - "3003:3003"
    
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge